### ISSUE TITLE
Wrong import in file train_sup_model.py

### ISSUE THREAD

**Issue by hbcccc** [Jlfj345wf/RAPO#2]
It seems that this supervised version ("train_sup_model.py" in Line 2) also imports run_dssm_trainning from "train_semi.py" 
in which procedure expand_dict is included in this file.

Should it be fixed with "from train import run_dssm_trainning"?

train_sup_model.py好像错误地引用了半监督版本的run_dssm_trainning，里面包含了迭代式的字典生成，不是sup版本本该的固定字典。

**Comment by Jlfj345wf** [comment]
Sorry for the confusion caused by the function name.

We set the parameter `args.load_model = 1` at line 27 in the file `train_sup_model.py`, which means that the training phase is performed only once and does not expand the dictionary.

抱歉我们的函数名字可能给您带来疑惑。请注意，在监督版本的运行脚本`train_sup_model.py`中，我们设置了参数`args.load_model = 1`。因此，虽然引用的是`train_semi.py`中的函数，但实际上训练过程只会发生一次，并且不会进行迭代式的字典生成。

**Comment by hbcccc** [comment]
感谢！
